import { BrowserBoundary } from "@/components/BrowserBoundary";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BrowserBoundary />
        <nav className="mx-auto flex max-w-3xl gap-4 p-4 text-sm">
          <a className="text-blue-600 underline" href="/">
            Home
          </a>
          <a className="text-blue-600 underline" href="/sign-in">
            Sign In
          </a>
          <a className="text-blue-600 underline" href="/users">
            Users
          </a>
          <a className="text-blue-600 underline" href="/users/2">
            User 2 (render error demo)
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
